// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQVUFmjq-xp42_YIRBBrKrXRkAEaqlYKk',
    appId: '1:967740303864:web:89af8b05b108341bb38e0d',
    messagingSenderId: '967740303864',
    projectId: 'appemployee-a3f3b',
    authDomain: 'appemployee-a3f3b.firebaseapp.com',
    storageBucket: 'appemployee-a3f3b.appspot.com',
    measurementId: 'G-P8HKCKG1XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXRCs_2oAOK8TBV3m_UnxzZ0cWn86snPk',
    appId: '1:967740303864:android:ce56725976bdce1ab38e0d',
    messagingSenderId: '967740303864',
    projectId: 'appemployee-a3f3b',
    storageBucket: 'appemployee-a3f3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMEv28JOTtMXzpm_xUEZ5kb6ekGP7Rb8',
    appId: '1:967740303864:ios:d7f5c72ffce26cd9b38e0d',
    messagingSenderId: '967740303864',
    projectId: 'appemployee-a3f3b',
    storageBucket: 'appemployee-a3f3b.appspot.com',
    iosBundleId: 'com.fahad.appattendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMEv28JOTtMXzpm_xUEZ5kb6ekGP7Rb8',
    appId: '1:967740303864:ios:d7f5c72ffce26cd9b38e0d',
    messagingSenderId: '967740303864',
    projectId: 'appemployee-a3f3b',
    storageBucket: 'appemployee-a3f3b.appspot.com',
    iosBundleId: 'com.fahad.appattendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQVUFmjq-xp42_YIRBBrKrXRkAEaqlYKk',
    appId: '1:967740303864:web:91e5048f689d0912b38e0d',
    messagingSenderId: '967740303864',
    projectId: 'appemployee-a3f3b',
    authDomain: 'appemployee-a3f3b.firebaseapp.com',
    storageBucket: 'appemployee-a3f3b.appspot.com',
    measurementId: 'G-VGDNJGZ1GD',
  );
}
